import Aside from '@/components/Aside/Aside';
import Card from '@/components/Card/Card';
import GenderFilter from '@/components/GenderFilter/GenderFilter';
import Header from '@/components/Header/Header';
import Head from 'next/head';
import { SWAPI } from '@/constants/endpoints';
import { RootState, wrapper } from '@/redux/store';
import { fetchDataSuccess } from '@/redux/swapiSlice';
import { useSelector } from 'react-redux';

export default function Home() {
  const { data, loading, error } = useSelector((state: RootState) => state.swapi);

  if (loading) return <div>Loading...</div>;
  if (error) return <div>Error: {error}</div>;

  return (
    <>
      <Head>
        <title>Hunter Stack Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main">
        <Aside />
        <div style={{ flex: 1 }}>
          <Header />
          <GenderFilter />
          <div className="cards-wrapper">
            {data?.results.map((item, index) => {
              return <Card key={index} {...item} />;
            })}
          </div>
        </div>
      </div>
    </>
  );
}

export const getServerSideProps = wrapper.getServerSideProps((store) => async () => {
  try {
    const response = await fetch(`${SWAPI}/planets`);
    const data = await response.json();

    store.dispatch(fetchDataSuccess(data));

    return { props: {} };
  } catch (error) {
    console.error('Error fetching data:', error);
    return { props: {} };
  }
});
