import Aside from '@/components/Aside/Aside';
import Card from '@/components/Card/Card';
import GenderFilter from '@/components/GenderFilter/GenderFilter';
import Header from '@/components/Header/Header';
import Head from 'next/head';
import { SWAPI } from '@/constants/endpoints';
import { Film, Person, Planet } from '@/types/swapi';

type Data = {
  count: number;
  next: string | null;
  previous: string | null;
  results: Person[] | Planet[] | Film[];
};

type HomeProps = {
  data: Data;
};

export default function Home({ data }: HomeProps) {
  return (
    <>
      <Head>
        <title>Hunter Stack Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main">
        <Aside />
        <div style={{ flex: 1 }}>
          <Header />
          <GenderFilter />
          <div className="cards-wrapper">
            {data.results.map((item, index) => {
              return <Card key={index} {...item} />;
            })}
          </div>
        </div>
      </div>
    </>
  );
}

export async function getServerSideProps() {
  const response = await fetch(`${SWAPI}/planets`);
  const data: Data = await response.json();

  return {
    props: { data },
  };
}
